[GATE 1734] Unit test coverage
Localvox/vivialconnect-java pull request #3
Opened 2017-11-21 19:11 UTC by dpitch40

All Java client library endpoints covered, all unit tests passing (when running offline and online).

2017-11-23 15:17 UTC, ghost requested changes
What are you using for tracking coverage? Can you add some reporting to it so we know the number? I briefly added Cobertura (see https://www.mkyong.com/qa/maven-cobertura-code-coverage-example/) and seems to hover around 50%

2017-11-29 15:13 UTC, dpitch40 commented
My understanding of this task was that I was simply aiming to cover every endpoint implemented in the Java client library. So I made a list of all the library methods that hit our API and checked them off as they were covered by unit tests. I will ask Nick to confirm.

2017-11-29 15:37 UTC, dpitch40 commented
Nick and I don't think 100% line coverage is worth the time investment now. His intention was simply to bring unit test coverage up to the standard of other libraries, and it now probably greatly exceeds that of the other libraries.

2017-11-29 18:30 UTC, nphcbm commented on src/main/java/net/vivialconnect/model/VivialConnectResource.java
> +        System.out.println(e.toString());
having all these print statements (even commented out ones) seems like a bad idea.

2017-11-29 18:30 UTC, nphcbm commented on src/main/java/net/vivialconnect/model/format/ListFormatter.java
> +    // public ListFormatter(){
Why are we leaving commented out code in our codebase?

2017-11-30 21:18 UTC, merged