Added Bulk Send to Vivial Connect SDK
Localvox/vivialconnect-java pull request #6
Opened 2019-08-07 13:03 UTC by magils

2019-08-07 19:07 UTC, warchiefx requested changes

2019-08-07 19:07 UTC, warchiefx commented on src/test/java/net/vivialconnect/tests/MessageTest.java
> +        message.setToNumbers(bulkSendNumberList);
Why setting this twice?

2019-08-07 19:07 UTC, warchiefx commented on src/test/java/net/vivialconnect/tests/MessageTest.java
> +        BulkInfo bulkInfo = getDataSource().sendBulk(message);
Shouldn't this be `message.sendBulk()`?

2019-08-07 19:07 UTC, warchiefx commented on src/main/java/net/vivialconnect/model/message/Message.java
> +    private String bulkId;
I'd prefer the Bulk API to be a separate object than re-using the Message class. Should be easier to understand. Thoughts?

2019-08-08 23:01 UTC, closed without merging

2019-08-08 23:02 UTC, magils commented
These feebacks were addressed in a new branch and new pull request
https://github.com/Localvox/vivialconnect-java/pull/7